apiVersion: v2
name: ensiasit-battleground
description: ENSIAS IT Battleground
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: traefik
  version: ~8.9.1
  repository: "https://containous.github.io/traefik-helm-chart"