api:
  service:
    name: api-service
    port: 8080
    targetPort: 8080

  deployment:
    name: api-deployment
    replicas: 1
    container:
      name: api-container
      image: ensiasitclub/ensiasit-battleground-api
      tag: latest
      containerPort: 8080
    envFilePath: .prod.env

  ingress:
    name: api-ingress

ui:
  service:
    name: ui-service
    port: 80
    targetPort: 80

  deployment:
    name: ui-deployment
    replicas: 1
    container:
      name: ui-container
      image: ensiasitclub/ensiasit-battleground-ui
      tag: latest
      containerPort: 80
  
  ingress:
    name: ui-ingress

mongodb:
  auth:
    enabled: false
