kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-{{ .Values.api.service.name }}"
spec:
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
    tier: api
  type: ClusterIP
